site:
  name: "trisystems.ru"
  timezone: "Europe/Moscow"

metrika:
  counter_id: 70863205
  goal_id: 0
  currency: "RUB"

reporting:
  llm_enabled: true
  language: "ru"

ym_webmaster:
  user_id: 44806260
  host_id: "https:trisystems.ru:443"

gsc:
  site_url: "https://trisystems.ru/"


